services:
  db:
    image: postgres:15
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: "${POSTGRES_USER:-docker}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-docker}"
      POSTGRES_DB: ${POSTGRES_DB:-tallerdb}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5431:5432
    # command: postgres -c shared_preload_libraries=pg_stat_statements -U docker -c pg_stat_statements.track=all -c max_connections=200
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -h localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s
volumes:
  db_data:
